# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Data type version
version: 2

# Personal info
name: Joonghoo Park
title: Graduate Student
email: joonghoo@kaist.ac.kr
website: www.github.com/joonghoo98

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: Github Link
  icon: fab fa-github
  url: https://www.github.com/joonghoo98
- title: Linkedin Link
  icon: fab fa-linkedin
  url: https://www.linkedin.com/in/joonghoo-park-a625a9341/
# - title: Google Scholar Link
#   icon: fab fa-google
#   url: https://scholar.google.com/

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/JH.jpg
about_content: | # this means to ignore newlines until the next config item.
  Hi, my name is Joonghoo Park. I am an Ph.D student in Industrial and Systems Engineering at KAIST.   
  My research interest is in analyzing, modeling, designing, and implementing algorithms for combinatorial optimization. 
  
#   - Methodologies: Linear programming, Integer programming, Branch-and-cut, Meta-heuristics
#   - Applications: Vehicle routing problems, Logistics, Facility location

content:
  - title: Education
    layout: list
    content:
      - layout: top
        title: KAIST (Korea Advanced Institute of Science and Technology)
        # sub_title: 2026 - 
        caption: 2026 -
        description: | # this will include new lines to allow paragraphs
          Ph.D in Industrial and Systems Engineering
      - layout: top
        title: Korea University
        # sub_title: 2023 - 2025
        caption: 2023 - 2025
        description: | # this will include new lines to allow paragraphs
          M.S. in Industrial Management Engineering
      - layout: top
        title: Pusan National University
        # sub_title: 2017 - 2023
        caption: 2017 - 2023
        description: | # this will include new lines to allow paragraphs
          B.S. in Urban Engineering (Double: Big Data Science)
   
  - title: Publications
    layout: list
    content:
      - layout: top
        title: International Journals
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - Seongjin Lee, Joonghoo Park, Seungmin Cha and Donghyun Kim* (2022), “A Regional Economy’s Resistance to the COVID-19 Shock: Sales Revenues of Micro-, Small-, and Medium-Sized Enterprises in South Korea”, International Journal of Disaster Risk Science
          - Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Integrated optimization of facility location and routing for timely emergency disaster response”, Under review at Transportation Research Part D: Transport and Environment 
          - (Works in Progress) Hyungjoo Cha, Joonghoo Park, Chungmok Lee* and Taesu Cheong*, "An Exact algorithm for Vehicle Routing Problem with Availability Profiles"
          - (Works in Progress) Joonghoo Park, Gwangjong Ko, Hyungjoo Cha and Taesu Cheong*, “Vehicle routing problem with metro based backhauls and MFCs”
          
          
  - title: Conferences
    layout: list
    content:
      - layout: top
        title: International Conferences
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Temporary medical shelter location-routing problem with manpower allocation in a disaster situation”, 2024 INFORMS Annual Meeting, Nov 2024.
          - Joonghoo Park, Gwangjong Ko and Taesu Cheong*, “Micro-fulfillment center location routing problem with underground logistics system”, 2024 International Conference of Asian Shipping and Logistics, Jun 2024.  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Samsung Display
        caption: Mar. 2024 - May. 2025
        description: | # this will include new lines to allow paragraphs
          Optimize facility planning by using optimization, Research Assistant @ Korea University
      - layout: top
        title: IITP
        caption: Feb. 2024 - Jun.2025
        description: | # this will include new lines to allow paragraphs
          Development of NetZero Building Energy Efficient System through AI-based HVAC system control, Information and Communication Planning and Evaluation Institute, Research Assistant @ Korea University 
      - layout: top
        title: Samsung Electronics
        caption: Nov. 2023 - Feb. 2024
        description: | # this will include new lines to allow paragraphs
          Maximize productivity by changing facility and logistics layouts Model development, Research Assistant @ Korea University
  
  - title: Research Experience
    layout: list
    content:
      - layout: top
        title: Korea Railroad Research Institute
        # sub_title: Research Intern
        caption: 2025 - 2025
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Researcher at Advanced Logistics Systems Lab, Korea Railroad Research Institute
      - layout: top
        title: Bigdata Analytics & Engineering Lab
        # sub_title: Research Intern
        caption: 2022 - 2023
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Bigdata Analytics & Engineering Lab, Pusan National University
      - layout: top
        title: Regional Development & Planning Lab
        # sub_title: Research Intern
        caption: 2021 - 2022
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Regional Development & Planning Lab, Pusan National University

  - title: Awards & Honors
    layout: list
    content:
      - layout: top
        title: Foundation of Korea Logistics Industry Promotion
        description: | # this will include new lines to allow paragraphs
          2nd Place, The 12th Research Paper Competition, 2025
      - layout: top
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Graduate School Mentor-Mentee Program, 2024
      - layout: top
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Future Talent Scholarship Student, 2023

  - title: Additional Information
    layout: list
    content:
      - layout: top
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
          - Python
          - C++
          - Julia
      - layout: top
        title: Optimization Software
        description: | # this will include new lines to allow paragraphs
          - CPLEX
          - Gurobi
      - layout: top
        title: Military Service
        caption: Jan. 2019 - Nov. 2020
        description: | # this will include new lines to allow paragraphs
          Republic of Korea Air Force

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
